baseurl = "https://antonjameslee.com/"
languageCode = "en-us"
theme = "minimalist"

[author]
  name = "Anton James Lee"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My new digital resume and blog"
  keywords = "homepage, blog, resume"
  images = [""]

  homeSubtitle="Programmer"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"

[languages]
  [languages.en]
    title = "Anton Lee"
    subtitle = "Programmer"
    keywords = ""
    copyright = "All rights reserved"
    readOtherPosts = "Read Other Posts"

    [languages.en.params.logo]
      logoText = "Anton Lee"
      logoHomeLink = "/"
      path = "/img/nGwEbV.png"
    # or
    #
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = 2

  [[menu.main]]
    identifier = "Posts"
    name       = "Posts"
    url        = "/posts/"
    weight     = 3

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects/"
    weight     = 4



  [[menu.main]]
    identifier = "linkedin"
    name       = "Linkedin"
    url        = "https://www.linkedin.com/in/anton-lee-0666471a5"
    weight     = 5

  [[menu.main]]
    identifier = "github"
    name       = "Github"
    url        = "https://github.com/tachyonicClock"
    weight     = 6

[markup.goldmark.renderer]
  unsafe= true